//
//  FileDigitsProviderTests.swift
//  PiTrainerTests
//
//  Generated by testarch-automate workflow
//

import XCTest
@testable import PiTrainer

final class FileDigitsProviderTests: XCTestCase {
    
    // MARK: - Valid Loading Tests
    
    func testLoadDigits_Pi_Success() {
        // Given
        var provider = FileDigitsProvider(constant: .pi)
        
        // When
        XCTAssertNoThrow(try provider.loadDigits())
        
        // Then
        XCTAssertGreaterThan(provider.totalDigits, 0, "Pi digits file should contain digits")
    }
    
    func testLoadDigits_E_Success() {
        // Given
        var provider = FileDigitsProvider(constant: .e)
        
        // When
        XCTAssertNoThrow(try provider.loadDigits())
        
        // Then
        XCTAssertGreaterThan(provider.totalDigits, 0, "E digits file should contain digits")
    }
    
    func testLoadDigits_Phi_Success() {
        // Given
        var provider = FileDigitsProvider(constant: .phi)
        
        // When
        XCTAssertNoThrow(try provider.loadDigits())
        
        // Then
        XCTAssertGreaterThan(provider.totalDigits, 0, "Phi digits file should contain digits")
    }
    
    // MARK: - Digit Access Tests
    
    func testGetDigit_ValidIndex_ReturnsDigit() {
        // Given
        var provider = FileDigitsProvider(constant: .pi)
        try? provider.loadDigits()
        
        // When
        let firstDigit = provider.getDigit(at: 0)
        
        // Then
        XCTAssertNotNil(firstDigit)
        XCTAssertEqual(firstDigit, 1, "First digit of Pi (after 3.) should be 1")
    }
    
    func testGetDigit_SecondDigit_ReturnsCorrectValue() {
        // Given
        var provider = FileDigitsProvider(constant: .pi)
        try? provider.loadDigits()
        
        // When
        let secondDigit = provider.getDigit(at: 1)
        
        // Then
        XCTAssertNotNil(secondDigit)
        XCTAssertEqual(secondDigit, 4, "Second digit of Pi should be 4 (3.14...)")
    }
    
    func testGetDigit_NegativeIndex_ReturnsNil() {
        // Given
        var provider = FileDigitsProvider(constant: .pi)
        try? provider.loadDigits()
        
        // When
        let digit = provider.getDigit(at: -1)
        
        // Then
        XCTAssertNil(digit, "Negative index should return nil")
    }
    
    func testGetDigit_IndexOutOfBounds_ReturnsNil() {
        // Given
        var provider = FileDigitsProvider(constant: .pi)
        try? provider.loadDigits()
        let outOfBoundsIndex = provider.totalDigits + 100
        
        // When
        let digit = provider.getDigit(at: outOfBoundsIndex)
        
        // Then
        XCTAssertNil(digit, "Out of bounds index should return nil")
    }
    
    // MARK: - Idempotent Loading Test
    
    func testLoadDigits_CalledMultipleTimes_DoesNotDuplicate() {
        // Given
        var provider = FileDigitsProvider(constant: .pi)
        try? provider.loadDigits()
        let initialCount = provider.totalDigits
        
        // When
        try? provider.loadDigits()
        try? provider.loadDigits()
        
        // Then
        XCTAssertEqual(provider.totalDigits, initialCount, "Loading multiple times should not change digit count")
    }
    
    // MARK: - All Digits Are Valid (0-9)
    
    func testAllDigits_AreValidRange() {
        // Given
        var provider = FileDigitsProvider(constant: .pi)
        try? provider.loadDigits()
        
        // When/Then
        for i in 0..<min(100, provider.totalDigits) {
            let digit = provider.getDigit(at: i)
            XCTAssertNotNil(digit)
            XCTAssertTrue((0...9).contains(digit!), "Digit at index \(i) should be 0-9, got \(digit!)")
        }
    }
    
    // MARK: - E Constant Validation
    
    func testGetDigit_E_FirstDigits() {
        // Given: e = 2.71828...
        var provider = FileDigitsProvider(constant: .e)
        try? provider.loadDigits()
        
        // Then: First digits after decimal should be 7, 1, 8, 2, 8
        XCTAssertEqual(provider.getDigit(at: 0), 7)
        XCTAssertEqual(provider.getDigit(at: 1), 1)
        XCTAssertEqual(provider.getDigit(at: 2), 8)
        XCTAssertEqual(provider.getDigit(at: 3), 2)
        XCTAssertEqual(provider.getDigit(at: 4), 8)
    }
    
    // MARK: - Phi Constant Validation
    
    func testGetDigit_Phi_FirstDigits() {
        // Given: φ = 1.61803...
        var provider = FileDigitsProvider(constant: .phi)
        try? provider.loadDigits()
        
        // Then: First digits after decimal should be 6, 1, 8, 0, 3
        XCTAssertEqual(provider.getDigit(at: 0), 6)
        XCTAssertEqual(provider.getDigit(at: 1), 1)
        XCTAssertEqual(provider.getDigit(at: 2), 8)
        XCTAssertEqual(provider.getDigit(at: 3), 0)
        XCTAssertEqual(provider.getDigit(at: 4), 3)
    }
}
